# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hoon/CLionProjects/ZoAD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hoon/CLionProjects/ZoAD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hoon/CLionProjects/ZoAD/CMakeFiles /home/hoon/CLionProjects/ZoAD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hoon/CLionProjects/ZoAD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ZoAD

# Build rule for target.
ZoAD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZoAD
.PHONY : ZoAD

# fast build rule for target.
ZoAD/fast:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/build
.PHONY : ZoAD/fast

IO_request.o: IO_request.cpp.o

.PHONY : IO_request.o

# target to build an object file
IO_request.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IO_request.cpp.o
.PHONY : IO_request.cpp.o

IO_request.i: IO_request.cpp.i

.PHONY : IO_request.i

# target to preprocess a source file
IO_request.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IO_request.cpp.i
.PHONY : IO_request.cpp.i

IO_request.s: IO_request.cpp.s

.PHONY : IO_request.s

# target to generate assembly for a file
IO_request.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IO_request.cpp.s
.PHONY : IO_request.cpp.s

IZG.o: IZG.cpp.o

.PHONY : IZG.o

# target to build an object file
IZG.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IZG.cpp.o
.PHONY : IZG.cpp.o

IZG.i: IZG.cpp.i

.PHONY : IZG.i

# target to preprocess a source file
IZG.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IZG.cpp.i
.PHONY : IZG.cpp.i

IZG.s: IZG.cpp.s

.PHONY : IZG.s

# target to generate assembly for a file
IZG.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/IZG.cpp.s
.PHONY : IZG.cpp.s

Partition.o: Partition.cpp.o

.PHONY : Partition.o

# target to build an object file
Partition.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Partition.cpp.o
.PHONY : Partition.cpp.o

Partition.i: Partition.cpp.i

.PHONY : Partition.i

# target to preprocess a source file
Partition.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Partition.cpp.i
.PHONY : Partition.cpp.i

Partition.s: Partition.cpp.s

.PHONY : Partition.s

# target to generate assembly for a file
Partition.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Partition.cpp.s
.PHONY : Partition.cpp.s

Userdata.o: Userdata.cpp.o

.PHONY : Userdata.o

# target to build an object file
Userdata.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Userdata.cpp.o
.PHONY : Userdata.cpp.o

Userdata.i: Userdata.cpp.i

.PHONY : Userdata.i

# target to preprocess a source file
Userdata.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Userdata.cpp.i
.PHONY : Userdata.cpp.i

Userdata.s: Userdata.cpp.s

.PHONY : Userdata.s

# target to generate assembly for a file
Userdata.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Userdata.cpp.s
.PHONY : Userdata.cpp.s

Zone.o: Zone.cpp.o

.PHONY : Zone.o

# target to build an object file
Zone.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Zone.cpp.o
.PHONY : Zone.cpp.o

Zone.i: Zone.cpp.i

.PHONY : Zone.i

# target to preprocess a source file
Zone.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Zone.cpp.i
.PHONY : Zone.cpp.i

Zone.s: Zone.cpp.s

.PHONY : Zone.s

# target to generate assembly for a file
Zone.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/Zone.cpp.s
.PHONY : Zone.cpp.s

controller.o: controller.c.o

.PHONY : controller.o

# target to build an object file
controller.c.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/controller.c.o
.PHONY : controller.c.o

controller.i: controller.c.i

.PHONY : controller.i

# target to preprocess a source file
controller.c.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/controller.c.i
.PHONY : controller.c.i

controller.s: controller.c.s

.PHONY : controller.s

# target to generate assembly for a file
controller.c.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/controller.c.s
.PHONY : controller.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/main.cpp.s
.PHONY : main.cpp.s

zoad.o: zoad.cpp.o

.PHONY : zoad.o

# target to build an object file
zoad.cpp.o:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/zoad.cpp.o
.PHONY : zoad.cpp.o

zoad.i: zoad.cpp.i

.PHONY : zoad.i

# target to preprocess a source file
zoad.cpp.i:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/zoad.cpp.i
.PHONY : zoad.cpp.i

zoad.s: zoad.cpp.s

.PHONY : zoad.s

# target to generate assembly for a file
zoad.cpp.s:
	$(MAKE) -f CMakeFiles/ZoAD.dir/build.make CMakeFiles/ZoAD.dir/zoad.cpp.s
.PHONY : zoad.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ZoAD"
	@echo "... edit_cache"
	@echo "... IO_request.o"
	@echo "... IO_request.i"
	@echo "... IO_request.s"
	@echo "... IZG.o"
	@echo "... IZG.i"
	@echo "... IZG.s"
	@echo "... Partition.o"
	@echo "... Partition.i"
	@echo "... Partition.s"
	@echo "... Userdata.o"
	@echo "... Userdata.i"
	@echo "... Userdata.s"
	@echo "... Zone.o"
	@echo "... Zone.i"
	@echo "... Zone.s"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... zoad.o"
	@echo "... zoad.i"
	@echo "... zoad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

